server:
  port: ${SERVER_PORT:8088}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ticket-service
          uri: lb://TICKET-SERVICE
          predicates:
            - Path=/ticket/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/schedule/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**,/auth/**
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
    register-with-eureka: false
  instance:
    preferIpAddress: true



